language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
script: coverage run --source=fprettify setup.py test
install:
 - pip install coveralls
before_script:
 - wget https://github.com/acmeism/RosettaCodeData/archive/bba7b.tar.gz
 - mkdir fortran_tests/before/RosettaCodeData && tar -xf bba7b.tar.gz -C fortran_tests/before/RosettaCodeData --strip-components=1
 - wget https://github.com/cp2k/cp2k/archive/ca7e2c.tar.gz
 - mkdir fortran_tests/before/cp2k && tar -xf ca7e2c.tar.gz -C fortran_tests/before/cp2k --strip-components=1
after_success:
 - coveralls
